name: my-badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update My Badges
        run: npx update-my-badges anupmazumdar --dir badges
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
